services:
  redis:
    image: redis:7-alpine
    container_name: ts_express_redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --requirepass mySecret123

  backend:
    build: .
    container_name: ts_express_backend
    restart: always
    ports:
      - "5001:5060"
    environment:
      DATABASE_URL: "postgresql://postgres.jkjcfgjoeijmphlrsolj:tAyuxQf3BSfjZHNv@aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres?pgbouncer=true&statement_cache_size=0&sslmode=require"
      REDIS_HOST: "redis" # 👈 ডকার নেটওয়ার্কে সার্ভিস নেম
      REDIS_PORT: 6379
      REDIS_PASSWORD: "mySecret123"
      NODE_ENV: "development"
      PORT: 5060
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - redis